hw4: main.o tablecheck.o encrypt.o decrypt.o encrypt3.o decrypt3.o
	gcc -o hw4 main.o tablecheck.o encrypt.o decrypt.o encrypt3.o decrypt3.o
main.o: main.c
	gcc -c main.c
tablecheck.o: tablecheck.c
	gcc -c tablecheck.c
encrypt.o: encrypt.c
	gcc -c encrypt.c
decrypt.o: decrypt.c
	gcc -c decrypt.c
encrypt3.o: encrypt3.c
	gcc -c encrypt3.c
decrypt3.o: decrypt3.c
	gcc -c decrypt3.c
clean:
	rm hw4 *.o

