hw3: main.c keygen.c crypt.c invken.c histo.c solve.c
	gcc -o hw3 main.c keygen.c crypt.c invken.c histo.c solve.c -L/home/scf-22/csci551b/openssl/lib -lcrypto -lm -I/home/scf-22/csci551b/openssl/include

clean:
	hw3

